version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - '80:80'
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      - MYSQL_HOST=host.docker.internal
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Highjump6!
      - MYSQL_DATABASE=forum
    ports:
      - '3001:3001'
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Highjump6!
      MYSQL_DATABASE: forum
    ports:
      - '3307:3307'
